export const Questions = {
  "numbers-alphabet" : [
    {id:0,  soru:"Zero, Two, Sixteen",           cevap:"0, 2, 16",   soruTurkce:"Zirou, Tu, Sikstiin",       cevapTurkce:""},
    {id:1,  soru:"Eighteen, Nine, Fourteen",     cevap:"18, 9, 14",  soruTurkce:"Eytiin, Nayn, Fortiin",     cevapTurkce:""},
    {id:2,  soru:"Three, Twelve, Six",           cevap:"3, 12, 6",   soruTurkce:"Tıri, Tvelf, Siks",         cevapTurkce:""},
    {id:3,  soru:"Twenty, Three, Seventeen",     cevap:"20, 3, 17",  soruTurkce:"Tıventi, Tıri, Sevıntiin",  cevapTurkce:""},
    {id:4,  soru:"Eleven, Fifteen, Ten",         cevap:"11, 15, 10", soruTurkce:"Elevın, Fiftiin, Ten",      cevapTurkce:""},
    {id:5,  soru:"Two, Nineteen, Thirteen",      cevap:"2, 19, 13",  soruTurkce:"Tu, Nayntiin, Törtiin",     cevapTurkce:""},
    {id:6,  soru:"Twelve, Twenty, Seventeen",    cevap:"12, 20, 17", soruTurkce:"Tvelf, Tıventi, Sevıntiin", cevapTurkce:""},
    {id:7,  soru:"Four, Nineteen, Five",         cevap:"4, 19, 5",   soruTurkce:"For, Nayntiin, Fayf",       cevapTurkce:""},
    {id:8,  soru:"Zero, Thirteen, Twelve",       cevap:"0, 13, 12",  soruTurkce:"Zirou, Törtiin, Tvelf",     cevapTurkce:""},
    {id:9,  soru:"Four, Thirteen, Twelve",       cevap:"4, 13, 12",  soruTurkce:"For, Törtiin, Tvelf",       cevapTurkce:""},
    {id:10, soru:"Twenty, Three, Fifteen",       cevap:"20, 3, 15",  soruTurkce:"Tıventi, Tıri, Fiftiin",    cevapTurkce:""},
    {id:11, soru:"Thirteen, Eight, Nineteen",    cevap:"13, 8, 19",  soruTurkce:"Törtiin, Eyt, Nayntiin",    cevapTurkce:""},
    {id:12, soru:"Eighteen, Sixteen, Eleven",    cevap:"18, 16, 11", soruTurkce:"Eytiin, Sikstiin, Elevın",  cevapTurkce:""},
    {id:13, soru:"Seventeen, Two, Twenty",       cevap:"17, 2, 20",  soruTurkce:"Sevıntiin, Tu, Tıventi",    cevapTurkce:""},
    {id:14, soru:"Thirteen, Three, Twelve",      cevap:"13, 3, 12",  soruTurkce:"Törtiin, Tıri, Tvelf",      cevapTurkce:""},
    {id:15, soru:"Fiat",        cevap:"ef, ay, ey, ti",                         soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
    {id:16, soru:"Mitsubisi",   cevap:"em, ay, ti, es, yu, bi, ay, es, ay",     soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
    {id:17, soru:"Hygrapy",     cevap:"eyc, vay, ci, ar, ey, pi, vay",          soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
    {id:18, soru:"Overview",    cevap:"ou, vi, i, ar, vi, ay, i, dablyu",       soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
    {id:19, soru:"Director",    cevap:"di, ay, ar, i, si, ti, ou, ar",          soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
    {id:20, soru:"Chief",       cevap:"si, eyc, ay, i, ef",                     soruTurkce:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", cevapTurkce:""},
  ],
  "greeting-farewell" : [
    {id:0, soru:"Hello", cevap:"Merhaba", soruTurkce:"(Resmi Selamlaşma)", cevapTurkce:""},
    {id:1, soru:"Hi", cevap:"Selam", soruTurkce:"", cevapTurkce:""},
    {id:2, soru:"Hi there", cevap:"Selamlar", soruTurkce:"(Hi deyır)", cevapTurkce:""},
    {id:3, soru:"Hey", cevap:"Selam", soruTurkce:"(Dikkat çekme amaçlı selam)", cevapTurkce:""},
    {id:4, soru:"Hello", cevap:"Alo", soruTurkce:"(Telefon açma)", cevapTurkce:""},
    {id:5, soru:"Good morning", cevap:"Günaydın", soruTurkce:"", cevapTurkce:""},
    {id:6, soru:"Good afnernoon", cevap:"Tünaydın", soruTurkce:"", cevapTurkce:""},
    {id:7, soru:"Good evening", cevap:"Iyi akşamlar", soruTurkce:"", cevapTurkce:""},
    {id:8, soru:"Good night", cevap:"Iyi geceler", soruTurkce:"", cevapTurkce:""},
    {id:9, soru:"Bye Bye", cevap:"Güle güle", soruTurkce:"", cevapTurkce:""},
    {id:10, soru:"See you", cevap:"Görüşürüz", soruTurkce:"", cevapTurkce:""},
    {id:11, soru:"See you letter", cevap:"Sonra görüşürüz", soruTurkce:"(Si yu leydır", cevapTurkce:""},
    {id:12, soru:"See you tomorrow", cevap:"Yarın görüşürüz", soruTurkce:"", cevapTurkce:""},
    {id:13, soru:"Have a nice day", cevap:"Iyi günler", soruTurkce:"Hev a nays dey", cevapTurkce:""},
    {id:14, soru:"Have a nice evening", cevap:"Iyi akşamlar", soruTurkce:"Hev a nays ivning", cevapTurkce:""},
    {id:15, soru:"Take care of yourself", cevap:"Kendine iyi bak", soruTurkce:"(Tek keyır of yorself)", cevapTurkce:""},
    {id:16, soru:"You too", cevap:"Sen de", soruTurkce:"", cevapTurkce:""},
    {id:17, soru:"Me too", cevap:"Ben de", soruTurkce:"", cevapTurkce:""},
    {id:18, soru:"Take care", cevap:"Kendine iyi bak", soruTurkce:"Kısaltılmış hali (Tek keyır)", cevapTurkce:""},
  ],
  "situation-ask" : [
    {id:0, soru:"How are you ?", cevap:"I am,fine.Thanks", soruTurkce:"Nasılsın ?", cevapTurkce:"İyiyim (fine), teşekkürler."},
    {id:1, soru:"Are you OK ?", cevap:"Not so good.", soruTurkce:"İyi misin ?", cevapTurkce:"Çok iyi değil."},
    {id:2, soru:"How are you ?", cevap:"I feel bad.", soruTurkce:"Nasılsın ?", cevapTurkce:"Kötü hissediyorum."},
    {id:3, soru:"How are you ?", cevap:"I am great.Thanks.", soruTurkce:"Nasılsın ?", cevapTurkce:"Harikayım. Teşekkürler."},
    {id:4, soru:"How are you ?", cevap:"Thanks. I am good. How about you ?", soruTurkce:"Nasılsın ?", cevapTurkce:"Teşekkürler. İyiyim, sen nasılsın ?"},
    {id:5, soru:"What's up ?", cevap:"So So", soruTurkce:"Naber ?", cevapTurkce:"Şöyle Böyle"},
    {id:6, soru:"What's up ?", cevap:"I am great. Thanks. What's up with you ?", soruTurkce:"Naber ?", cevapTurkce:"Harikayim. Teşekkürler. Senden naber ?"},
    {id:7, soru:"How are you doing ?", cevap:"I am doing great, thanks for asking.", soruTurkce:"Nasıl gidiyor ?", cevapTurkce:"Harika gidiyor. Sorduğun için teşekkürler."},
    {id:8, soru:"What's new ?", cevap:"Not much.", soruTurkce:"Hayatında yeni bir şeyler var mı ?", cevapTurkce:"Fazla bir yenilik yok."},
    {id:9, soru:"Is everything alright ?", cevap:"Yes, everything is OK", soruTurkce:"Her şey yolunda mı ?", cevapTurkce:"Evet, her şey yolunda."},
    {id:10, soru:"What’s going on ?", cevap:"Keeping busy", soruTurkce:"Neler yapıyorsun, hayatında neler oluyor ?", cevapTurkce:"Meşgulum, uğraşıp duruyorum.(Keping bizi)"},
    {id:11, soru:"How is business ?", cevap:"Same as usual", soruTurkce:"İşler nasıl ?", cevapTurkce:"Her zamanki gibi. (Seym es yüjıvo"},
    {id:12, soru:"Are you OK?", cevap:"I am OK. Thanks for asking.", soruTurkce:"İyi misin ?", cevapTurkce:"İyiyim. Soruduğun için teşekkürler."},
    {id:13, soru:"How are you feeling ?", cevap:"I'm tired.And you ?", soruTurkce:"Nasıl hissediyorsun ?", cevapTurkce:"Yorgunum (I'm). Sen nasıl hissediyorsun ?(and)"},
    {id:14, soru:"How are you feeling ?", cevap:"I'm cool", soruTurkce:"Nasıl hissediyorsun ?", cevapTurkce:"Ben iyiyim.(I'm)"},
    {id:15, soru:"What’s happening?", cevap:"No complaints.", soruTurkce:"Hayatın nasıl gidiyor ? (vats heappinin)", cevapTurkce:"Şikayetim yok. (No kompileynts)"},
    {id:16, soru:"How are you doing ?", cevap:"Not bad.", soruTurkce:"Nasıl gidiyor ?", cevapTurkce:"Kötü değil, fena değil."},
    {id:17, soru:"Are you OK?", cevap:"I am great. How about you ?", soruTurkce:"İyi misin ?", cevapTurkce:"Harikayım. Sen nasılsın ?"},
  ],
  "to-meet" : [
    {id:0, soru:"What is your name ?", cevap:"My name is Burak.", soruTurkce:"Senin adın ne ? (What is)", cevapTurkce:"Benim adım Burak."},
    {id:1, soru:"What's your name ?", cevap:"I am Burak, and you ?", soruTurkce:"Senin adın ne ? (What's)", cevapTurkce:"Ben Burak, ya sen ?"},
    {id:2, soru:"What's your name ?", cevap:"My name is Burak, and you ?", soruTurkce:"Senin adın ne ?", cevapTurkce:"Benim ismim Burak, ya seninki ?"},
    {id:3, soru:"Hi.I am Burak. What's your name ?", cevap:"Hi. My name is Kaira. Nice to meet you.", soruTurkce:"Selam. Ben Burak. Senin adın ne ?", cevapTurkce:"Selam. Benim adım Kaira. Seninle tanışmak güzel."},
    {id:4, soru:"Hey. My name is Kaira, and you ?", cevap:"Hi Kaira. I am Burak. Pleased to meet you.", soruTurkce:"Selam. Benim adım Kaira, ya seninki ?", cevapTurkce:"Selam Kaira. Ben Burak. Tanıştığımıza memnun oldum. (Pilisdt tu mit yu)"},
    {id:5, soru:"My name is Kaira.", cevap:"Glad to meet you.", soruTurkce:"Benim adım Kaira.", cevapTurkce:"Tanıştığımıza sevindim.(Gılad tu mit yu)"},
    {id:6, soru:"I'm Burak.", cevap:"A pleasure to meet you.", soruTurkce:"Ben Burak.", cevapTurkce:"Seninle tanışmak bir zevk.(e pilejır tu mit yu)"},
    {id:7, soru:"I am happy to meet you.", cevap:"Nice to meet you too.", soruTurkce:"Seninle tanıştığıma memnun oldum.", cevapTurkce:"Bende seninle tanıştığıma memnun oldum."},
    {id:8, soru:"Where are you from ?", cevap:"I am from Turkey. Which city ?", soruTurkce:"Nerelisin ?", cevapTurkce:"Türkiyeliyim. Hangi şehir ?"},
    {id:9, soru:"Are you from İstanbul ?", cevap:"Yes, I am", soruTurkce:"İstanbul 'dan mısın ?", cevapTurkce:"Evet öyleyim."},
    {id:10, soru:"I am from Turkey, how about you ?", cevap:"I am from Canada.", soruTurkce:"Türkiyeliyim, sen nerelisin ?", cevapTurkce:"Ben Kanadalıyım."},
    {id:11, soru:"Where do you live ?", cevap:"I live in İstanbul, and you ?", soruTurkce:"Nerede yaşıyorsun ?(veer du yu liv)", cevapTurkce:"İstanbul 'da yaşıyorum, ya sen ?"},
    {id:12, soru:"Are you from England ?", cevap:"No. I am not. And you ?", soruTurkce:"İngiltere 'den misin ?", cevapTurkce:"Hayır, değilim. Ya sen ?"},
    {id:13, soru:"How old are you ?", cevap:"I am 15 years old.", soruTurkce:"Kaç yaşındasın ?", cevapTurkce:"Ben 15 yaşındayım."},
    {id:14, soru:"How old is she ?", cevap:"She is 20 years old.", soruTurkce:"O (kız) kaç yaşında ?", cevapTurkce:"O (kız) 20 yaşında."},
    {id:15, soru:"How old is your father ?", cevap:"My father is 40 years old.", soruTurkce:"Baban kaç yaşında ?", cevapTurkce:"Babam 40 yaşında (veya He/She is)"},
    {id:16, soru:"How old is your mother ?", cevap:"She is 40 years old.", soruTurkce:"Annen kaç yaşında ?", cevapTurkce:"O (kız) 40 yaşında (veya My mother)"},
  ],
  "days-months-years" : [
    {id:0, soru:"Monday",       cevap:"Pazartesi",  soruTurkce:"Man-dey",       cevapTurkce:""},
    {id:1, soru:"Tuesday",      cevap:"Salı",       soruTurkce:"Tuuz-dey",      cevapTurkce:""},
    {id:2, soru:"Wednesday",    cevap:"Çarşamba",   soruTurkce:"Wenz-dey",      cevapTurkce:""},
    {id:3, soru:"Thursday",     cevap:"Perşembe",   soruTurkce:"Törz-dey",      cevapTurkce:""},
    {id:4, soru:"Friday",       cevap:"Cuma",       soruTurkce:"Fıray-dey",     cevapTurkce:""},
    {id:5, soru:"Saturday",     cevap:"Cumartesi",  soruTurkce:"Satır-dey",     cevapTurkce:""},
    {id:6, soru:"Sunday",       cevap:"Pazar",      soruTurkce:"San-dey",       cevapTurkce:""},
    {id:7, soru:"Year",         cevap:"Yıl",        soruTurkce:"Yiır",          cevapTurkce:""},
    {id:8, soru:"Month",        cevap:"Ay",         soruTurkce:"Mant",          cevapTurkce:""},
    {id:9, soru:"Week",         cevap:"Hafta",      soruTurkce:"Wiik",          cevapTurkce:""},
    {id:10, soru:"Weekend",     cevap:"Haftasonu",  soruTurkce:"Wiik-end",      cevapTurkce:""},
    {id:11, soru:"Weekdays",    cevap:"Haftaiçi",   soruTurkce:"Wiik-deys",     cevapTurkce:""},
    {id:12, soru:"Day",         cevap:"Gün",        soruTurkce:"Dey",           cevapTurkce:""},
    {id:13, soru:"January",     cevap:"Ocak",       soruTurkce:"Ce-nu-e-ri",    cevapTurkce:""},
    {id:14, soru:"February",    cevap:"Şubat",      soruTurkce:"Feb-ru-e-ri",   cevapTurkce:""},
    {id:15, soru:"March",       cevap:"Mart",       soruTurkce:"Març",          cevapTurkce:""},
    {id:16, soru:"April",       cevap:"Nisan",      soruTurkce:"Ep-rıl",        cevapTurkce:""},
    {id:17, soru:"May",         cevap:"Mayıs",      soruTurkce:"Mey",           cevapTurkce:""},
    {id:18, soru:"June",        cevap:"Haziran",    soruTurkce:"Cun",           cevapTurkce:""},
    {id:19, soru:"July",        cevap:"Temmuz",     soruTurkce:"Cu-lay",        cevapTurkce:""},
    {id:20, soru:"August",      cevap:"Ağustos",    soruTurkce:"Ou-gıst",       cevapTurkce:""},
    {id:21, soru:"September",   cevap:"Eylül",      soruTurkce:"Sep-tem-bır",   cevapTurkce:""},
    {id:22, soru:"October",     cevap:"Ekim",       soruTurkce:"Ok-to-bır",     cevapTurkce:""},
    {id:23, soru:"November",    cevap:"Kasım",      soruTurkce:"No-vem-bır",    cevapTurkce:""},
    {id:24, soru:"December",    cevap:"Aralık",     soruTurkce:"Di-sem-bır",    cevapTurkce:""},
  ]
  
};
