export const Questions = {
  "numbers-alphabet" : [
    {id:0,  question:"Zero, Two, Sixteen",           answer:"0, 2, 16",   questionTurkish:"Zirou, Tu, Sikstiin",       answerTurkish:""},
    {id:1,  question:"Eighteen, Nine, Fourteen",     answer:"18, 9, 14",  questionTurkish:"Eytiin, Nayn, Fortiin",     answerTurkish:""},
    {id:2,  question:"Three, Twelve, Six",           answer:"3, 12, 6",   questionTurkish:"Tıri, Tvelf, Siks",         answerTurkish:""},
    {id:3,  question:"Twenty, Three, Seventeen",     answer:"20, 3, 17",  questionTurkish:"Tıventi, Tıri, Sevıntiin",  answerTurkish:""},
    {id:4,  question:"Eleven, Fifteen, Ten",         answer:"11, 15, 10", questionTurkish:"Elevın, Fiftiin, Ten",      answerTurkish:""},
    {id:5,  question:"Two, Nineteen, Thirteen",      answer:"2, 19, 13",  questionTurkish:"Tu, Nayntiin, Törtiin",     answerTurkish:""},
    {id:6,  question:"Twelve, Twenty, Seventeen",    answer:"12, 20, 17", questionTurkish:"Tvelf, Tıventi, Sevıntiin", answerTurkish:""},
    {id:7,  question:"Four, Nineteen, Five",         answer:"4, 19, 5",   questionTurkish:"For, Nayntiin, Fayf",       answerTurkish:""},
    {id:8,  question:"Zero, Thirteen, Twelve",       answer:"0, 13, 12",  questionTurkish:"Zirou, Törtiin, Tvelf",     answerTurkish:""},
    {id:9,  question:"Four, Thirteen, Twelve",       answer:"4, 13, 12",  questionTurkish:"For, Törtiin, Tvelf",       answerTurkish:""},
    {id:10, question:"Twenty, Three, Fifteen",       answer:"20, 3, 15",  questionTurkish:"Tıventi, Tıri, Fiftiin",    answerTurkish:""},
    {id:11, question:"Thirteen, Eight, Nineteen",    answer:"13, 8, 19",  questionTurkish:"Törtiin, Eyt, Nayntiin",    answerTurkish:""},
    {id:12, question:"Eighteen, Sixteen, Eleven",    answer:"18, 16, 11", questionTurkish:"Eytiin, Sikstiin, Elevın",  answerTurkish:""},
    {id:13, question:"Seventeen, Two, Twenty",       answer:"17, 2, 20",  questionTurkish:"Sevıntiin, Tu, Tıventi",    answerTurkish:""},
    {id:14, question:"Thirteen, Three, Twelve",      answer:"13, 3, 12",  questionTurkish:"Törtiin, Tıri, Tvelf",      answerTurkish:""},
    {id:15, question:"Fiat",        answer:"ef, ay, ey, ti",                         questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
    {id:16, question:"Mitsubisi",   answer:"em, ay, ti, es, yu, bi, ay, es, ay",     questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
    {id:17, question:"Hygrapy",     answer:"eyc, vay, ci, ar, ey, pi, vay",          questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
    {id:18, question:"Overview",    answer:"ou, vi, i, ar, vi, ay, i, dablyu",       questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
    {id:19, question:"Director",    answer:"di, ay, ar, i, si, ti, ou, ar",          questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
    {id:20, question:"Chief",       answer:"si, eyc, ay, i, ef",                     questionTurkish:"Yukarıdaki kelimenin harflerini ingilizce okunuşu ile yazınız.", answerTurkish:""},
  ],
  "greeting-farewell" : [
    {id:0, question:"Hello", answer:"Merhaba", questionTurkish:"(Resmi Selamlaşma)", answerTurkish:""},
    {id:1, question:"Hi", answer:"Selam", questionTurkish:"", answerTurkish:""},
    {id:2, question:"Hi there", answer:"Selamlar", questionTurkish:"(Hi deyır)", answerTurkish:""},
    {id:3, question:"Hey", answer:"Selam", questionTurkish:"(Dikkat çekme amaçlı selam)", answerTurkish:""},
    {id:4, question:"Hello", answer:"Alo", questionTurkish:"(Telefon açma)", answerTurkish:""},
    {id:5, question:"Good morning", answer:"Günaydın", questionTurkish:"", answerTurkish:""},
    {id:6, question:"Good afnernoon", answer:"Tünaydın", questionTurkish:"", answerTurkish:""},
    {id:7, question:"Good evening", answer:"Iyi akşamlar", questionTurkish:"", answerTurkish:""},
    {id:8, question:"Good night", answer:"Iyi geceler", questionTurkish:"", answerTurkish:""},
    {id:9, question:"Bye Bye", answer:"Güle güle", questionTurkish:"", answerTurkish:""},
    {id:10, question:"See you", answer:"Görüşürüz", questionTurkish:"", answerTurkish:""},
    {id:11, question:"See you letter", answer:"Sonra görüşürüz", questionTurkish:"(Si yu leydır", answerTurkish:""},
    {id:12, question:"See you tomorrow", answer:"Yarın görüşürüz", questionTurkish:"", answerTurkish:""},
    {id:13, question:"Have a nice day", answer:"Iyi günler", questionTurkish:"Hev a nays dey", answerTurkish:""},
    {id:14, question:"Have a nice evening", answer:"Iyi akşamlar", questionTurkish:"Hev a nays ivning", answerTurkish:""},
    {id:15, question:"Take care of yourself", answer:"Kendine iyi bak", questionTurkish:"(Tek keyır of yorself)", answerTurkish:""},
    {id:16, question:"You too", answer:"Sen de", questionTurkish:"", answerTurkish:""},
    {id:17, question:"Me too", answer:"Ben de", questionTurkish:"", answerTurkish:""},
    {id:18, question:"Take care", answer:"Kendine iyi bak", questionTurkish:"Kısaltılmış hali (Tek keyır)", answerTurkish:""},
  ],
  "situation-ask" : [
    {id:0, question:"How are you ?", answer:"I am,fine.Thanks", questionTurkish:"Nasılsın ?", answerTurkish:"İyiyim (fine), teşekkürler."},
    {id:1, question:"Are you OK ?", answer:"Not so good.", questionTurkish:"İyi misin ?", answerTurkish:"Çok iyi değil."},
    {id:2, question:"How are you ?", answer:"I feel bad.", questionTurkish:"Nasılsın ?", answerTurkish:"Kötü hissediyorum."},
    {id:3, question:"How are you ?", answer:"I am great.Thanks.", questionTurkish:"Nasılsın ?", answerTurkish:"Harikayım. Teşekkürler."},
    {id:4, question:"How are you ?", answer:"Thanks. I am good. How about you ?", questionTurkish:"Nasılsın ?", answerTurkish:"Teşekkürler. İyiyim, sen nasılsın ?"},
    {id:5, question:"What's up ?", answer:"So So", questionTurkish:"Naber ?", answerTurkish:"Şöyle Böyle"},
    {id:6, question:"What's up ?", answer:"I am great. Thanks. What's up with you ?", questionTurkish:"Naber ?", answerTurkish:"Harikayim. Teşekkürler. Senden naber ?"},
    {id:7, question:"How are you doing ?", answer:"I am doing great, thanks for asking.", questionTurkish:"Nasıl gidiyor ?", answerTurkish:"Harika gidiyor. Sorduğun için teşekkürler."},
    {id:8, question:"What's new ?", answer:"Not much.", questionTurkish:"Hayatında yeni bir şeyler var mı ?", answerTurkish:"Fazla bir yenilik yok."},
    {id:9, question:"Is everything alright ?", answer:"Yes, everything is OK", questionTurkish:"Her şey yolunda mı ?", answerTurkish:"Evet, her şey yolunda."},
    {id:10, question:"What’s going on ?", answer:"Keeping busy", questionTurkish:"Neler yapıyorsun, hayatında neler oluyor ?", answerTurkish:"Meşgulum, uğraşıp duruyorum.(Keping bizi)"},
    {id:11, question:"How is business ?", answer:"Same as usual", questionTurkish:"İşler nasıl ?", answerTurkish:"Her zamanki gibi. (Seym es yüjıvo"},
    {id:12, question:"Are you OK?", answer:"I am OK. Thanks for asking.", questionTurkish:"İyi misin ?", answerTurkish:"İyiyim. questionduğun için teşekkürler."},
    {id:13, question:"How are you feeling ?", answer:"I'm tired.And you ?", questionTurkish:"Nasıl hissediyorsun ?", answerTurkish:"Yorgunum (I'm). Sen nasıl hissediyorsun ?(and)"},
    {id:14, question:"How are you feeling ?", answer:"I'm cool", questionTurkish:"Nasıl hissediyorsun ?", answerTurkish:"Ben iyiyim.(I'm)"},
    {id:15, question:"What’s happening?", answer:"No complaints.", questionTurkish:"Hayatın nasıl gidiyor ? (vats heappinin)", answerTurkish:"Şikayetim yok. (No kompileynts)"},
    {id:16, question:"How are you doing ?", answer:"Not bad.", questionTurkish:"Nasıl gidiyor ?", answerTurkish:"Kötü değil, fena değil."},
    {id:17, question:"Are you OK?", answer:"I am great. How about you ?", questionTurkish:"İyi misin ?", answerTurkish:"Harikayım. Sen nasılsın ?"},
  ],
  "to-meet" : [
    {id:0, question:"What is your name ?", answer:"My name is Burak.", questionTurkish:"Senin adın ne ? (What is)", answerTurkish:"Benim adım Burak."},
    {id:1, question:"What's your name ?", answer:"I am Burak, and you ?", questionTurkish:"Senin adın ne ? (What's)", answerTurkish:"Ben Burak, ya sen ?"},
    {id:2, question:"What's your name ?", answer:"My name is Burak, and you ?", questionTurkish:"Senin adın ne ?", answerTurkish:"Benim ismim Burak, ya seninki ?"},
    {id:3, question:"Hi.I am Burak. What's your name ?", answer:"Hi. My name is Kaira. Nice to meet you.", questionTurkish:"Selam. Ben Burak. Senin adın ne ?", answerTurkish:"Selam. Benim adım Kaira. Seninle tanışmak güzel."},
    {id:4, question:"Hey. My name is Kaira, and you ?", answer:"Hi Kaira. I am Burak. Pleased to meet you.", questionTurkish:"Selam. Benim adım Kaira, ya seninki ?", answerTurkish:"Selam Kaira. Ben Burak. Tanıştığımıza memnun oldum. (Pilisdt tu mit yu)"},
    {id:5, question:"My name is Kaira.", answer:"Glad to meet you.", questionTurkish:"Benim adım Kaira.", answerTurkish:"Tanıştığımıza sevindim.(Gılad tu mit yu)"},
    {id:6, question:"I'm Burak.", answer:"A pleasure to meet you.", questionTurkish:"Ben Burak.", answerTurkish:"Seninle tanışmak bir zevk.(e pilejır tu mit yu)"},
    {id:7, question:"I am happy to meet you.", answer:"Nice to meet you too.", questionTurkish:"Seninle tanıştığıma memnun oldum.", answerTurkish:"Bende seninle tanıştığıma memnun oldum."},
    {id:8, question:"Where are you from ?", answer:"I am from Turkey. Which city ?", questionTurkish:"Nerelisin ?", answerTurkish:"Türkiyeliyim. Hangi şehir ?"},
    {id:9, question:"Are you from İstanbul ?", answer:"Yes, I am", questionTurkish:"İstanbul 'dan mısın ?", answerTurkish:"Evet öyleyim."},
    {id:10, question:"I am from Turkey, how about you ?", answer:"I am from Canada.", questionTurkish:"Türkiyeliyim, sen nerelisin ?", answerTurkish:"Ben Kanadalıyım."},
    {id:11, question:"Where do you live ?", answer:"I live in İstanbul, and you ?", questionTurkish:"Nerede yaşıyorsun ?(veer du yu liv)", answerTurkish:"İstanbul 'da yaşıyorum, ya sen ?"},
    {id:12, question:"Are you from England ?", answer:"No. I am not. And you ?", questionTurkish:"İngiltere 'den misin ?", answerTurkish:"Hayır, değilim. Ya sen ?"},
    {id:13, question:"How old are you ?", answer:"I am 15 years old.", questionTurkish:"Kaç yaşındasın ?", answerTurkish:"Ben 15 yaşındayım."},
    {id:14, question:"How old is she ?", answer:"She is 20 years old.", questionTurkish:"O (kız) kaç yaşında ?", answerTurkish:"O (kız) 20 yaşında."},
    {id:15, question:"How old is your father ?", answer:"My father is 40 years old.", questionTurkish:"Baban kaç yaşında ?", answerTurkish:"Babam 40 yaşında (veya He/She is)"},
    {id:16, question:"How old is your mother ?", answer:"She is 40 years old.", questionTurkish:"Annen kaç yaşında ?", answerTurkish:"O (kız) 40 yaşında (veya My mother)"},
  ],
  "days-months-years" : [
    {id:0, question:"Monday",       answer:"Pazartesi",  questionTurkish:"Man-dey",       answerTurkish:""},
    {id:1, question:"Tuesday",      answer:"Salı",       questionTurkish:"Tuuz-dey",      answerTurkish:""},
    {id:2, question:"Wednesday",    answer:"Çarşamba",   questionTurkish:"Wenz-dey",      answerTurkish:""},
    {id:3, question:"Thursday",     answer:"Perşembe",   questionTurkish:"Törz-dey",      answerTurkish:""},
    {id:4, question:"Friday",       answer:"Cuma",       questionTurkish:"Fıray-dey",     answerTurkish:""},
    {id:5, question:"Saturday",     answer:"Cumartesi",  questionTurkish:"Satır-dey",     answerTurkish:""},
    {id:6, question:"Sunday",       answer:"Pazar",      questionTurkish:"San-dey",       answerTurkish:""},
    {id:7, question:"Year",         answer:"Yıl",        questionTurkish:"Yiır",          answerTurkish:""},
    {id:8, question:"Month",        answer:"Ay",         questionTurkish:"Mant",          answerTurkish:""},
    {id:9, question:"Week",         answer:"Hafta",      questionTurkish:"Wiik",          answerTurkish:""},
    {id:10, question:"Weekend",     answer:"Haftasonu",  questionTurkish:"Wiik-end",      answerTurkish:""},
    {id:11, question:"Weekdays",    answer:"Haftaiçi",   questionTurkish:"Wiik-deys",     answerTurkish:""},
    {id:12, question:"Day",         answer:"Gün",        questionTurkish:"Dey",           answerTurkish:""},
    {id:13, question:"January",     answer:"Ocak",       questionTurkish:"Ce-nu-e-ri",    answerTurkish:""},
    {id:14, question:"February",    answer:"Şubat",      questionTurkish:"Feb-ru-e-ri",   answerTurkish:""},
    {id:15, question:"March",       answer:"Mart",       questionTurkish:"Març",          answerTurkish:""},
    {id:16, question:"April",       answer:"Nisan",      questionTurkish:"Ep-rıl",        answerTurkish:""},
    {id:17, question:"May",         answer:"Mayıs",      questionTurkish:"Mey",           answerTurkish:""},
    {id:18, question:"June",        answer:"Haziran",    questionTurkish:"Cun",           answerTurkish:""},
    {id:19, question:"July",        answer:"Temmuz",     questionTurkish:"Cu-lay",        answerTurkish:""},
    {id:20, question:"August",      answer:"Ağustos",    questionTurkish:"Ou-gıst",       answerTurkish:""},
    {id:21, question:"September",   answer:"Eylül",      questionTurkish:"Sep-tem-bır",   answerTurkish:""},
    {id:22, question:"October",     answer:"Ekim",       questionTurkish:"Ok-to-bır",     answerTurkish:""},
    {id:23, question:"November",    answer:"Kasım",      questionTurkish:"No-vem-bır",    answerTurkish:""},
    {id:24, question:"December",    answer:"Aralık",     questionTurkish:"Di-sem-bır",    answerTurkish:""},
  ]
  
};
